Portfolio: Mobile Version
RiyaBulia12/Portfolio pull request #1
Opened 2022-06-29 13:00 UTC by RiyaBulia12

This Project accomplishes [Portfolio: setup and mobile version skeleton](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/1_setup.md) and contains the following:

- Added two sections in the Portfolio webpage:
     - Header Section: This section is displayed using flexbox. It has a logo and menu button which changes the cursor on hovering the menu button
     - Introduction Section: This section also has a flexbox. It contains the main title, sub-title, and social media section. When the user hovers on each social media icon it changes the pointer to the hand cursor.
- Added Linters to check HTML and CSS syntax
- Added Readme, and gitignore
NOTE: I am using [Figma Template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122)

**_Result Screenshot:_**
<img width="373" alt="Screenshot 2022-06-29 at 6 16 32 PM" src="https://user-images.githubusercontent.com/24832846/176441111-61890795-5129-4616-a915-2aac0fc6791e.png">

2022-06-29 14:38 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @RiyaBulia12 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-29 14:38 UTC, tresorsawasawa commented on index.html
> +            <div class="social-media-title">Let's Connect</div>
- [ ] Kindly make sure the sub-title(e.g.: Let's Conn...) uses a header tag `<hx> (examples: <h2>,<h3>, etc...)` as it a **sub-title** introducing the social links. This will make your code follow the HTML good semantics and as required for the project.

2022-06-29 14:38 UTC, tresorsawasawa commented on index.html
> +   </body>
- [ ] **IMPORTANT**: Kindly make sure when you add a new change to check if it doesn't affect the styling, but it affects the styling make sure to fix it to make your project stick to the Figma design

2022-06-29 14:38 UTC, tresorsawasawa commented on README.md
> +
- [ ] Kindly make sure you add a good title to your project to make your documentation looks more professional. I suggest you reolace the `# Project Name` text to your `Project title`.

- [ ] Once you are done with the title make sure you update your project description(" > Welcome to my Portfolio... ") to good description that tells users what is about your project. This will make your README looks more professional.

2022-06-29 14:38 UTC, tresorsawasawa commented on README.md
> +
- [ **OPTIONAL** ] **IMPORTANT:** I think it would be better if you improve the **Setup sub-section** by adding hints(commands lines) on how to clone the repository in the local machine. 
- [ **OPTIONAL** ] **IMPORTANT:** And if possible you can wrap all the command lines inside `back-sticks(``)` so they will look smart and help users know that they are command lines.
I suggest you use t[his README as an example](https://github.com/tresorsawasawa/MyPortfolio/blob/develop/README.md), you can copy the inside content by clicking(`copy raw content button`) to have everything inside, then edit it according your project information.

2022-06-29 18:09 UTC, vickymarz requested changes
Hi @RiyaBulia12 , 

Great work on making the changes requested by a previous reviewer 👏 🔥 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## Top highlight 🎯

- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-29 18:09 UTC, vickymarz commented on index.html
> +      </main>
- [ ] As mentioned by the previous reviewer, kindly make sure that your design matches the one given in the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1). I can see that the background images are missing in your design 📱 . 

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/63473584/176505053-748822e4-772c-4e2d-b267-8d448d716845.png)   |![image](https://user-images.githubusercontent.com/63473584/176505159-957ca8d3-5739-4ecc-b102-59eb05844f8f.png)
  |

**IMPORTANT:** - When you add the background images, make sure they are specified as `background images`  in the CSS file. and not` <img>` tags. Good job so far 😄

2022-06-29 18:27 UTC, RiyaBulia12 commented on index.html
> +      </main>
Hello @vickymarz, thanks for reviewing my PR. When I run my project locally I am getting the expected result(Please see attached). Not sure how can I fix the issue. Can you please suggest a way how can I replicate the same view you are getting?

<img width="1188" alt="Screenshot 2022-06-29 at 11 56 15 PM" src="https://user-images.githubusercontent.com/24832846/176509267-20975250-5a88-404f-9d5a-5819abbd239f.png">
.

2022-06-30 12:17 UTC, Lucas-Masaba approved these changes
# Hello @RiyaBulia12  👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![almost-there](https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif)

## Highlights 🍾 
- Linter checks passing ✔️ 
- Done changes requested b previous reviewer 👍 
- Descriptive README 📜 
- Good pull request description 🏄 
- Meaningful commit messages 🏂 

## Optional suggestions 💭 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 12:23 UTC, merged